jobs:
- job: 
  pool: 'server'
  steps:
  - task: ManualIntervention@8
    timeoutInMinutes: 1440
    inputs:
      instructions: 'Please validate the build configuration and resume'
      emailRecipients: 'jesse.houwing@gmail.com'